export const copy = {
  brand: "Averie 做饭档案",
  nav: {
    cooked: "做过的",
    wantCook: "想做的",
    wantEat: "想吃的",
  },
  empty: {
    cooked: "还没记下第一道菜。做完一顿，回来留个脚印吧。",
    wantCook: "以后想试的菜，先收在这里。",
    wantEat: "还没有人点「想吃」。看好的，点一下就留在这。",
  },
  btn: {
    wantEat: "想吃",
    cancelWantEat: "取消想吃",
    wanted: "已想吃",
    rate: "评个分",
    rerate: "改评分",
    submit: "提交",
    login: "登录评分",
    loginOwner: "站长登录",
    logout: "退出",
    detail: "查看详情",
    back: "返回",
    retry: "再试一次",
    register: "登录 / 注册",
  },
  lock: {
    title: "完整食谱仅站长可见。",
    sub: "登录后才能打开步骤与用料；访客可以浏览简介、评分，并点「想吃」。",
  },
  rating: {
    none: "暂无评分",
    unit: "/ 10",
    title: "这道菜怎么样",
    scale: "10 分制",
    pick: "点选 1–10 分（每人一票）",
    people: (n: number) => `${n} 人评`,
    yours: (n: number) => `你评了 ${n} 分 · 再点只改你的分数，不另算一个人`,
    yoursShort: (n: number) => `你评了 ${n} 分`,
  },
  account: {
    title: "登录评分",
    hint: "取个昵称和 4–6 位数字 PIN。第一次即注册，以后同一组就能找回自己的分数。每个人账号分开。",
    name: "昵称",
    pin: "PIN（4–6 位数字）",
    skip: "也可以先匿名评分，本机会尽量记住你。",
    nudge: "取个昵称，换手机也能改自己的分数。",
    ratingAs: (name: string) => `正在用「${name}」评分`,
    logoutConfirm: "退出后本机不再用这个账号评分。账号和已打的分还在，下次用昵称和 PIN 就能找回。确定退出？",
    loggedIn: (name: string) => `已登录为 ${name}`,
  },
  coverLoading: "封面载入中",
  searchPlaceholder: "搜索菜名",
  allCategories: "全部",
  categoriesNav: "分类",
  noMatch: "没有符合的菜。换个分类或关键词试试。",
  ownerNoRecipe: "这道菜还没有写入完整食谱。",
  wantEatCount: (n: number) => `${n} 人想吃`,
  loadError: "没加载出来，再试一次？",
  slowError: "网络有点慢，再试一次？",
  offlineRatings: "网络不通，评分暂不可用",
  loginHint: "只有站长能改档案、看完整食谱",
  cookedMark: "做过",
} as const;
