import {useRef,useState,type FormEvent} from 'react';
import {Link,Navigate,useLocation,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {useAuth} from './lib/auth';
import {request} from './lib/api';
import {api,useJournal} from './lib/journal';
export function AccountPage(){
 const {rater,loginRater,logoutRater}=useAuth(),navigate=useNavigate(),[params]=useSearchParams();const [name,setName]=useState(''),[pin,setPin]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const next=params.get('next')||'/';
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await loginRater(name,pin);navigate(next.startsWith('/')&&!next.startsWith('//')?next:'/');}catch(e){setError(e instanceof Error?e.message:'登录失败');}finally{setBusy(false);}}
 return <div className="form-page"><div className="eyebrow">YOUR SEAT AT THE TABLE</div><h1>{rater?`你好，${rater.displayName}`:'给自己留个座位'}</h1><p className="muted">第一次用昵称和 PIN 注册，以后同一组登录。这个设备会长期记住你。</p>{rater?<><p>你可以上传菜品、评分、点菜和留言。</p><Link className="primary-button" to="/">回到家食记</Link><button className="text-button" onClick={logoutRater}>退出这个账号</button></>:<form onSubmit={submit}><label>昵称<input required autoComplete="username" name="username" maxLength={16} value={name} onChange={e=>setName(e.target.value)}/></label><label>PIN · 4–6 位数字<input required type="password" name="password" inputMode="numeric" autoComplete="current-password" pattern="[0-9]{4,6}" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy}>{busy?'正在入座…':'登录 / 注册'}</button><p className="form-hint">刷新或关闭网页不会退出，网络不好也不会。只有主动退出、清除浏览器数据或凭证失效后才需要重新登录。</p></form>}</div>;
}
async function uploadImage(file:File){
 if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error('请选择 JPEG、PNG 或 WebP 图片');
 if(file.size>20*1024*1024)throw new Error('请选择小于20MB的图片');
 const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('浏览器无法处理图片');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('图片压缩失败')),'image/jpeg',.88));if(blob.size>2*1024*1024)throw new Error('请选择更小的图片');const form=new FormData();form.append('file',blob,'photo.jpg');return request<{coverPath:string}>('/api/journal/upload',{method:'POST',body:form});
}
export function CreatePage(){
 const {type}=useParams(),[params]=useSearchParams(),{rater}=useAuth(),{data,refresh}=useJournal(),navigate=useNavigate(),loc=useLocation(),home=params.get('kind')!=='out',id=useRef(crypto.randomUUID()),entryId=useRef(crypto.randomUUID());
 const [title,setTitle]=useState(''),[location,setLocation]=useState(''),[categories,setCategories]=useState(''),[ingredients,setIngredients]=useState(''),[steps,setSteps]=useState(''),[notes,setNotes]=useState(''),[source,setSource]=useState(''),[target,setTarget]=useState(params.get('target')||''),[date,setDate]=useState(()=>{const n=new Date();return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`}),[meal,setMeal]=useState('晚餐'),[status,setStatus]=useState('want_cook'),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[phase,setPhase]=useState('');const coverPath=useRef<string|undefined>();
 if(!['dish','restaurant','entry'].includes(type||''))return <Navigate to="/" replace/>;
 const isEntry=type==='entry',isDish=type==='dish',list=home?data?.dishes:data?.restaurants;
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(file&&!coverPath.current){setPhase('正在处理照片与滤镜…');coverPath.current=(await uploadImage(file)).coverPath;}setPhase('正在记下来…');
 if(isEntry)await api('/entries','POST',{id:id.current,kind:home?'home':'out',targetId:target,date,meal,notes,coverPath:coverPath.current});
 else if(isDish){await api('/dishes','POST',{id:id.current,title,status,categories:categories.split(/[,，]/).map(s=>s.trim()).filter(Boolean),recipe:{ingredients:ingredients.split('\n').filter(Boolean),steps:steps.split('\n').filter(Boolean),notes},sourceUrl:source,coverPath:coverPath.current});if(status==='cooked')await api('/entries','POST',{id:entryId.current,kind:'home',targetId:id.current,date,meal,notes,coverPath:coverPath.current});}
 else{await api('/restaurants','POST',{id:id.current,title,location,categories:categories.split(/[,，]/).map(s=>s.trim()).filter(Boolean),notes,coverPath:coverPath.current});if(params.get('want')==='1')await api(`/wants/restaurant/${id.current}`,'PUT',{wanted:true});}
 await refresh();navigate(isEntry?(home?'/':'/out'):isDish?`/library?tab=${status}&detail=dish:${id.current}`:'/orders?tab=restaurant');
 }catch(e){setError(e instanceof Error?e.message:'没有保存成功，请重试');}finally{setBusy(false);}}
 return <div className="form-page wide"><Link className="text-button" to={isEntry?(home?'/':'/out'):isDish?'/library':'/orders?tab=restaurant'}>← 返回</Link><div className="eyebrow">A NEW LITTLE MEMORY</div><h1>{isEntry?'记下这一餐':isDish?'添一道好味道':'记住一家新店'}</h1>{!rater?<><p className="muted">登录后就能一起记录。</p><Link className="primary-button" to={`/login?next=${encodeURIComponent(loc.pathname+loc.search)}`}>登录 / 注册</Link></>:<form onSubmit={submit}>{isEntry?<><label>{home?'这次做了哪道菜':'这次去了哪家店'}<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">请选择</option>{list?.map(i=><option key={i.id} value={i.id}>{i.title}{'location'in i?` · ${i.location}`:''}</option>)}</select></label><Link className="text-button" to={home?'/new/dish':'/new/restaurant'}>列表没有？先添加{home?'菜品':'餐厅'} →</Link></>:<><label>{isDish?'菜名':'餐厅名称'}<input required maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/></label>{!isDish&&<label>地点 · 城市 / 区域<input required maxLength={120} value={location} onChange={e=>setLocation(e.target.value)} placeholder="例如：京都 · 祇园"/></label>}<label>分类 · 用逗号分开<input value={categories} onChange={e=>setCategories(e.target.value)} placeholder={isDish?'例如：中餐，牛肉，主食':'例如：日料，咖啡，旅行'}/></label></>}{isDish&&<><label>收在哪里<select value={status} onChange={e=>setStatus(e.target.value)}><option value="want_cook">想做的</option><option value="cooked">已做的（同时记录制作日期）</option></select></label><label>用料 · 每行一项<textarea rows={4} value={ingredients} onChange={e=>setIngredients(e.target.value)} placeholder="食材与份量"/></label><label>做法 · 每行一步<textarea rows={5} value={steps} onChange={e=>setSteps(e.target.value)}/></label><label>灵感来源链接<input type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="小红书或其他来源链接"/></label></>}{(isEntry||(isDish&&status==='cooked'))&&<div className="form-two"><label>用餐日期<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>哪一餐<select value={meal} onChange={e=>setMeal(e.target.value)}>{['早餐','午餐','晚餐','下午茶','夜宵','其他'].map(m=><option key={m}>{m}</option>)}</select></label></div>}<label>{isEntry?'这一餐的笔记':'备注'}<textarea rows={3} maxLength={5000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="upload-label">{isEntry?'这一次的照片':'封面照片'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setFile(e.target.files?.[0]||null);coverPath.current=undefined;}}/><span className="form-hint">照片会压缩，并应用已设定的美食滤镜。</span></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy}>{busy?phase:'保存这份记录'}</button></form>}</div>;
}
