import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,useLocation,useSearchParams} from 'react-router-dom';
import {useAuth} from './lib/auth';
import {api,useJournal,score,tags,type Entry} from './lib/journal';
import {Icon,Photo,WantButton,useDetail} from './JournalUI';
type Comment={id:string;author:string;body:string;createdAt:string;mine:boolean};
function Comments({scope,id}:{scope:string;id:string}){
 const {rater}=useAuth(),{refresh}=useJournal(),loc=useLocation();const [comments,setComments]=useState<Comment[]|null>(null),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const res=await api<{comments:Comment[]}>(`/comments/${scope}/${id}`);setComments(res.comments);}
 useEffect(()=>{let active=true;setComments(null);setError('');setBody('');api<{comments:Comment[]}>(`/comments/${scope}/${id}`).then(r=>{if(active)setComments(r.comments)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false};},[scope,id]);
 async function send(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(`/comments/${scope}/${id}`,'POST',{body});setBody('');await load();await refresh();}catch(e){setError(e instanceof Error?e.message:'留言失败');}finally{setBusy(false);}}
 async function remove(commentId:string){setBusy(true);setError('');try{await api(`/comments/${scope}/${commentId}`,'DELETE');await load();await refresh();}catch(e){setError(e instanceof Error?e.message:'删除失败');}finally{setBusy(false);}}
 return <section className="comments"><h3>{scope==='board'?'这次点菜，想说的话':scope==='entry'?'这一餐的留言':'留言小记'}<small>{comments?.length??''}</small></h3>{scope==='board'&&<p className="muted">只在榜单可见，最后一人取消想吃后清除。</p>}{error&&<p role="alert" className="form-error">{error}</p>}{comments===null&&!error?<p className="muted">正在翻开留言…</p>:comments?.length?comments.map(c=><div key={c.id} className="comment"><div><strong>{c.author}</strong><time>{new Date(c.createdAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time>{c.mine&&<button disabled={busy} onClick={()=>void remove(c.id)}>删除</button>}</div><p>{c.body}</p></div>):!error&&<p className="muted">还没有留言，写下第一句吧。</p>}{rater?<form onSubmit={send}><label className="sr-only" htmlFor="comment-body">写留言</label><textarea id="comment-body" value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} rows={3} placeholder={scope==='board'?'比如：周末一起吃这个吧。':'记下一点感想…'}/><button className="primary-button" disabled={busy||!body.trim()}>{busy?'正在保存…':'留下这句'}</button></form>:<Link className="outline-button" to={`/login?next=${encodeURIComponent(loc.pathname+loc.search)}`}>登录后留言</Link>}</section>;
}
function RatingEditor({entry}:{entry:Entry}){const {rater}=useAuth(),{refresh,live}=useJournal(),loc=useLocation();const [busy,setBusy]=useState(false),[error,setError]=useState('');async function rate(n:number){setBusy(true);setError('');try{await api(`/entries/${entry.id}/rating`,'PUT',{score:n});await refresh();}catch(e){setError(e instanceof Error?e.message:'评分失败');}finally{setBusy(false);}}return <section className="rating-editor"><h3>这一餐，你打几分？</h3><p className="muted">{entry.myScore===null?'十分制 · 每个人一份评分，可修改':`你评了 ${entry.myScore} 分 · 重新选择即可改分`}</p>{rater?<div className="score-options" aria-label="评分1到10">{Array.from({length:10},(_,i)=>i+1).map(n=><button key={n} aria-pressed={entry.myScore===n} className={entry.myScore===n?'active':''} disabled={busy||!live} onClick={()=>void rate(n)}>{n}</button>)}</div>:<Link className="outline-button" to={`/login?next=${encodeURIComponent(loc.pathname+loc.search)}`}>登录后评分</Link>}{error&&<p className="form-error" role="alert">{error}</p>}</section>;}
function Recipe({id}:{id:string}){const [recipe,setRecipe]=useState<Record<string,unknown>|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);useEffect(()=>{let active=true;setRecipe(null);setError('');api<{recipe:Record<string,unknown>}>(`/dishes/${id}`).then(r=>{if(active)setRecipe(r.recipe)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false};},[id,retry]);const labels:Record<string,string>={summary:'关于这道菜',ingredients:'用料',ingredients_v1:'原版用料',ingredients_v2_next:'下次调整',steps:'做法',tasting:'品尝笔记',improvements:'下次改进',calories:'热量',notes:'备注'};const display=(v:unknown)=>typeof v==='string'||typeof v==='number'?String(v):JSON.stringify(v,null,2);return <section className="recipe"><h3>食谱手记</h3>{error?<p className="form-error">{error}<button onClick={()=>setRetry(n=>n+1)}>重试</button></p>:!recipe?<p className="muted">正在翻开食谱…</p>:!Object.keys(recipe).length?<p className="muted">这道菜的食谱还在整理，先把灵感收好。</p>:Object.entries(recipe).filter(([,v])=>v!=null&&v!==''&&(!Array.isArray(v)||v.length)).map(([key,value])=><div className="recipe-part" key={key}><h4>{labels[key]||key}</h4>{Array.isArray(value)?key==='steps'?<ol>{value.map((v,i)=><li key={i}>{display(v)}</li>)}</ol>:<ul>{value.map((v,i)=><li key={i}>{display(v)}</li>)}</ul>:<p>{display(value)}</p>}</div>)}</section>;}
export function DetailDialog(){
 const [params,set]=useSearchParams(),{data}=useJournal(),raw=params.get('detail'),[scope,id]=raw?.split(':')||[],ref=useRef<HTMLDialogElement>(null),open=useDetail();const close=()=>set(p=>{const n=new URLSearchParams(p);n.delete('detail');return n;},{replace:true});
 useEffect(()=>{const d=ref.current;if(raw){if(d&&!d.open)d.showModal();const prior=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prior;};}else d?.close();},[raw]);if(!raw)return null;
 const entry=scope==='entry'?data?.entries.find(e=>e.id===id):undefined,board=scope==='board'?data?.boards.find(b=>b.id===id):undefined,kind=entry?(entry.kind==='home'?'dish':'restaurant'):board?.kind||scope,targetId=entry?.targetId||board?.targetId||id,item=kind==='dish'?data?.dishes.find(d=>d.id===targetId):data?.restaurants.find(r=>r.id===targetId),missing=!item||(scope==='entry'&&!entry)||(scope==='board'&&!board);
 return <dialog className="detail-dialog" ref={ref} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}} aria-labelledby="detail-title"><div className="dialog-content"><button className="close-button" aria-label="关闭详情" onClick={close}><Icon name="close"/></button>{missing?<div className="detail-inner"><h2 id="detail-title">{scope==='board'?'这轮点菜结束了':'暂时找不到这条记录'}</h2><p className="muted">{scope==='board'?'最后一人已取消想吃，本轮榜单留言也已清除。':'请返回列表刷新后重试。'}</p></div>:<>{scope!=='board'&&<Photo url={entry?.coverUrl||item.coverUrl} title={item.title}/>}<div className="detail-inner"><div className="eyebrow">{board?'ON THE WISH LIST':entry?`${entry.date} ${entry.meal}`:kind==='dish'?'FROM OUR RECIPE SHELF':'A PLACE TO REMEMBER'}</div><h2 id="detail-title">{item.title}</h2><p className="muted">{'location'in item?item.location:tags(item).join(' · ')}</p><div className="detail-meta"><span className="detail-score">{score((entry||item).ratingAvg)}<small>{(entry||item).ratingAvg!==null?' / 10':''}</small></span><WantButton kind={kind as 'dish'|'restaurant'} item={item}/></div>{entry?<><p className="detail-notes">{entry.notes}</p><RatingEditor entry={entry}/><button className="text-button" onClick={()=>open(kind,targetId)}>{kind==='dish'?'查看完整食谱与菜品留言':'查看餐厅与历次到访'} →</button><Comments key={entry.id} scope="entry" id={entry.id}/></>:board?<Comments key={board.id} scope="board" id={board.id}/>:<>{kind==='dish'?<><Recipe id={targetId}/>{'sourceUrl'in item&&item.sourceUrl&&/^https?:\/\//i.test(item.sourceUrl)&&<a className="source-link" href={item.sourceUrl} target="_blank" rel="noreferrer">查看原始灵感 ↗</a>}</>:<p className="detail-notes">{'notes'in item?item.notes:''}</p>}<section className="visit-history"><h3>{kind==='dish'?'餐桌上的这些天':'来过的这些天'}</h3>{data?.entries.filter(e=>e.targetId===targetId&&e.kind===(kind==='dish'?'home':'out')).map(e=><button key={e.id} onClick={()=>open('entry',e.id)}><span>{e.date} {e.meal}</span><span>{score(e.ratingAvg)} →</span></button>)}<Link className="text-button" to={`/new/entry?kind=${kind==='dish'?'home':'out'}&target=${targetId}`}>＋ 记录这次{kind==='dish'?'制作':'到访'}</Link></section><Comments key={kind+targetId} scope={kind} id={targetId}/></>}</div></>}</div></dialog>;
}
