import {BrowserRouter,Link,NavLink,Navigate,Route,Routes,useLocation,useParams} from 'react-router-dom';
import {AuthProvider,useAuth} from './lib/auth';
import {JournalProvider,useJournal,tags} from './lib/journal';
import {Icon,Heading,Filters,useFilters,Blank,Skeleton,Card,WantButton,useDetail} from './JournalUI';
import {DetailDialog} from './JournalDetail';
import {AccountPage,CreatePage} from './JournalForms';
import './journal.css';
const nav=[['/','家食记','bowl'],['/out','外食记','out'],['/library','食物库','book'],['/orders','点菜','heart']];
function Shell(){const {rater,logoutRater}=useAuth(),loc=useLocation(),{data,error,loading,refresh}=useJournal();return <div className="journal-shell"><header className="site-header"><Link to="/" className="brand"><Icon size={32}/><span>Averie<span className="brand-sub">好好吃饭 · 慢慢记录</span></span></Link><div className="account-link">{rater?<><Link to="/login">{rater.displayName}</Link><button onClick={logoutRater}>退出</button></>:<Link to={`/login?next=${encodeURIComponent(loc.pathname+loc.search)}`}>登录</Link>}</div></header><nav className="main-nav" aria-label="主要页面">{nav.map(([to,label,icon],i)=><NavLink key={to} to={to} end={to==='/'}><span className="nav-number">0{i+1}</span><Icon name={icon}/><span>{label}</span></NavLink>)}</nav><main>{error&&<div className="network-note" role="status"><span>{data?'当前显示已保存的记录。':''}{error}</span><button disabled={loading} onClick={()=>void refresh()}>{loading?'正在重试…':'重试'}</button></div>}<Routes><Route path="/" element={<DiaryPage kind="home"/>}/><Route path="/out" element={<DiaryPage kind="out"/>}/><Route path="/library" element={<LibraryPage/>}/><Route path="/orders" element={<OrdersPage/>}/><Route path="/login" element={<AccountPage/>}/><Route path="/new/:type" element={<CreatePage key={loc.pathname+loc.search}/>}/><Route path="/dishes/:id" element={<LegacyDish/>}/><Route path="/want-cook" element={<Navigate to="/library?tab=want_cook" replace/>}/><Route path="/want-eat" element={<Navigate to="/orders" replace/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></main><footer className="site-footer"><span>一餐一饭，都是日子。</span><Icon name="leaf" size={20}/><span>AVERIE’S TABLE</span></footer><DetailDialog/></div>;}
function LegacyDish(){const {id}=useParams();return <Navigate to={`/library?detail=dish:${id}`} replace/>;}
function DiaryPage({kind}:{kind:'home'|'out'}){const {data}=useJournal(),f=useFilters(),home=kind==='home',items=home?data?.dishes:data?.restaurants;const byId=new Map((items||[]).map(item=>[item.id,item]));const entries=(data?.entries||[]).filter(e=>e.kind===kind&&byId.has(e.targetId));const options=[...new Set((items||[]).flatMap(i=>home?tags(i):['location'in i?i.location:'',...tags(i)]).filter(Boolean))],q=f.q.trim().toLowerCase();const visible=entries.filter(e=>{const item=byId.get(e.targetId)!;return (!f.date||e.date===f.date)&&(!f.category||tags(item).includes(f.category)||('location'in item&&item.location===f.category))&&(!q||[item.title,e.date,e.notes,e.meal,...tags(item),'location'in item?item.location:''].join(' ').toLowerCase().includes(q));});const dates=[...new Set(visible.map(e=>e.date))].sort((a,b)=>b.localeCompare(a));return <><Heading eyebrow={home?'AT HOME / 日常的滋味':'OUT & ABOUT / 寻味途中'} title={home?'家食记':'外食记'} sub={home?'把每天的饭，和喜欢它的理由，一起留下。':'记住一家店，也记住一起吃饭的那一天。'} icon={home?'bowl':'out'} action={<Link className="outline-button" to={`/new/entry?kind=${kind}`}><Icon name="plus" size={16}/>记一餐</Link>}/><Filters placeholder={home?'搜菜名、用餐笔记…':'搜餐厅、城市、用餐笔记…'} options={options} date/>{!data?<Skeleton/>:!dates.length?<Blank>{entries.length?'没有找到，换个关键词或日期试试。':home?'餐桌还空着，记下今天的第一餐吧。':'下一家喜欢的餐厅，从这里记起。'}</Blank>:<div className="card-grid diary-grid">{visible.map((e,index)=><div className="dated-card" key={e.id}><div className="entry-date"><time dateTime={e.date}>{e.date.slice(5).replace('-',' / ')}</time><small>{e.date.slice(0,4)} · {new Intl.DateTimeFormat('zh-CN',{weekday:'short',timeZone:'UTC'}).format(new Date(e.date+'T12:00:00Z'))}</small></div><Card item={byId.get(e.targetId)!} entry={e} kind={home?'dish':'restaurant'} index={index}/></div>)}</div>}</>;}

function LibraryPage(){const {data}=useJournal(),f=useFilters(),tab=f.params.get('tab')==='want_cook'?'want_cook':'cooked',dishes=(data?.dishes||[]).filter(d=>d.status===tab),q=f.q.trim().toLowerCase(),visible=dishes.filter(d=>(!f.category||tags(d).includes(f.category))&&(!q||[d.title,...tags(d)].join(' ').toLowerCase().includes(q)));return <><Heading eyebrow="THE RECIPE SHELF / 一起积攒" title="食物库" sub="做过的好味道，和下一次想尝试的灵感。" icon="book" action={<Link className="outline-button" to="/new/dish"><Icon name="plus" size={16}/>上传菜品</Link>}/><div className="page-tabs">{(['cooked','want_cook'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>f.change('tab',t)}>{t==='cooked'?'已做的':'想做的'}<small>{data?.dishes.filter(d=>d.status===t).length||0}</small></button>)}</div><Filters placeholder="搜索菜名、食材分类…" options={[...new Set(dishes.flatMap(tags))]}/><p className="list-caption">{visible.length} 道菜 · 食谱对所有人开放 · 分数汇总自家食记</p>{!data?<Skeleton/>:!visible.length?<Blank>{dishes.length?'没有找到，换个关键词或分类试试。':'把下一道想做的菜收进来吧。'}</Blank>:<div className="card-grid">{visible.map((d,i)=><Card key={d.id} item={d} kind="dish" index={i}/>)}</div>}</>;}
function OrdersPage(){const {data}=useJournal(),f=useFilters(),open=useDetail(),tab=f.params.get('tab')==='restaurant'?'restaurant':'dish',boards=(data?.boards||[]).filter(b=>b.kind===tab);return <><Heading eyebrow="NEXT ON THE TABLE / 想吃就点" title="点菜" sub="最近想吃的，放在前面。下次就从这里选。" icon="heart" action={tab==='restaurant'?<Link className="outline-button" to="/new/restaurant?want=1"><Icon name="plus" size={16}/>添加新店</Link>:<Link className="outline-button" to="/library">去食物库点菜</Link>}/><div className="page-tabs"><button className={tab==='dish'?'active':''} onClick={()=>f.change('tab','dish')}>菜品想吃榜<small>{data?.boards.filter(b=>b.kind==='dish').length||0}</small></button><button className={tab==='restaurant'?'active':''} onClick={()=>f.change('tab','restaurant')}>餐厅想吃榜<small>{data?.boards.filter(b=>b.kind==='restaurant').length||0}</small></button></div><p className="list-caption">按最近一次有效点菜时间排序 · 榜单留言仅保留到本轮点菜结束</p>{!data?<Skeleton/>:!boards.length?<Blank>还没有点菜，留一个下次想吃的念头吧。</Blank>:<ol className="order-list">{boards.map((b,index)=>{const item=b.kind==='dish'?data.dishes.find(d=>d.id===b.targetId):data.restaurants.find(r=>r.id===b.targetId);if(!item)return null;return <li key={b.id}><span className="rank">{String(index+1).padStart(2,'0')}</span><div className="order-main"><button className="order-title" onClick={()=>open(b.kind,b.targetId)}>{item.title}</button><p>{'location'in item?item.location:item.status==='cooked'?'已做过':'想做'}<span> · {new Date(b.lastWantedAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</span></p><button className="board-comment-link" onClick={()=>open('board',b.id)}><Icon name="chat" size={15}/>点菜留言 {b.commentCount}</button></div><WantButton kind={b.kind} item={b} compact/></li>;})}</ol>}</>;}
export function JournalApp(){return <AuthProvider><BrowserRouter basename={import.meta.env.BASE_URL.replace(/\/$/,'')}><JournalProvider><Shell/></JournalProvider></BrowserRouter></AuthProvider>;}
