import {useEffect,useState,type ReactNode} from 'react';
import {useLocation,useNavigate,useSearchParams} from 'react-router-dom';
import {useAuth} from './lib/auth';
import {api,useJournal,photoUrl,score,tags,type Food,type Restaurant,type Board,type Entry} from './lib/journal';
export function Icon({name='bowl',size=22}:{name?:string;size?:number}){
 const paths:Record<string,string>={bowl:'M3 10q9-2 18 0c-1 8-4 10-9 10S4 17 3 10Z M6 4l13 3M8 1l11 6M8 22h8',out:'M3 9h18L18 3H6L3 9ZM5 10v11h14V10M9 21v-7h6v7M3 9q3 4 6 0 3 4 6 0 3 4 6 0',book:'M3 3q5-2 9 1 5-3 9-1v17q-5-2-9 1-5-3-9-1V3ZM12 4v17M6 8h3M6 12h3M15 8h3M15 12h3',heart:'M12 21C-5 10 4-2 12 6 20-2 29 10 12 21Z',search:'M16 10a6 6 0 1 1-12 0 6 6 0 1 1 12 0ZM15 15l6 6',chat:'M4 4q8-2 16 0v12q-5 2-10 0l-6 5V4Z',plus:'M12 4v16M4 12h16',close:'m5 5 14 14M5 19 19 5',leaf:'M4 20C0 4 15 3 21 3c0 12-6 19-17 17ZM4 20 17 7M9 15v-5M13 11h5'};
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.bowl}/></svg>;
}
export function Heading({eyebrow,title,sub,action,icon='bowl'}:{eyebrow:string;title:string;sub:string;action?:ReactNode;icon?:string}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}<span className="heading-dot">.</span></h1><p>{sub}</p></div><div className="heading-side"><div className="heading-doodle"><Icon name={icon} size={57}/></div>{action}</div></div>;}
export function useFilters(){const [params,set]=useSearchParams();const change=(key:string,value:string)=>set(p=>{const n=new URLSearchParams(p);value?n.set(key,value):n.delete(key);return n;},{replace:true});return {params,change,q:params.get('q')||'',category:params.get('category')||'',date:params.get('date')||''};}
export function Filters({placeholder,options,date=false}:{placeholder:string;options:string[];date?:boolean}){const f=useFilters();return <div className="filters"><div className="search-row"><label className="search"><Icon name="search" size={19}/><input type="search" aria-label={placeholder} placeholder={placeholder} value={f.q} onChange={e=>f.change('q',e.target.value)}/></label>{date&&<label className="date-filter"><span>日期</span><input type="date" aria-label="按日期筛选" value={f.date} onChange={e=>f.change('date',e.target.value)}/>{f.date&&<button aria-label="清除日期" onClick={()=>f.change('date','')}>×</button>}</label>}</div><div className="category-row" aria-label="分类筛选">{['',...options].map(c=><button key={c} className={f.category===c?'selected':''} aria-pressed={f.category===c} onClick={()=>f.change('category',c)}>{c||'全部'}</button>)}</div></div>;}
export function Blank({children}:{children:ReactNode}){return <div className="empty"><Icon name="leaf" size={38}/><p>{children}</p></div>;}
export function Skeleton(){return <div className="card-grid" aria-label="记录载入中" aria-busy="true">{[1,2,3,4].map(n=><div key={n} className="card-skeleton"/>)}</div>;}
export function useDetail(){const [,set]=useSearchParams();return (kind:string,id:string)=>set(p=>{const n=new URLSearchParams(p);n.set('detail',kind+':'+id);return n;});}
export function Photo({url,title,priority=false}:{url:string|null;title:string;priority?:boolean}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[url]);const src=photoUrl(url);return <div className="food-photo">{src&&!failed?<img src={src} alt={title} width="480" height="360" loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'} decoding="async" onError={()=>setFailed(true)}/>:<div className="photo-placeholder"><Icon size={52}/><span>等待一张餐桌照片</span></div>}</div>;}
export function WantButton({kind,item,compact=false}:{kind:'dish'|'restaurant';item:Food|Restaurant|Board;compact?:boolean}){
 const {rater}=useAuth(),{refresh,live}=useJournal(),navigate=useNavigate(),loc=useLocation();const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function toggle(){if(!rater){navigate(`/login?next=${encodeURIComponent(loc.pathname+loc.search)}`);return;}setBusy(true);setError('');try{await api(`/wants/${kind}/${'targetId' in item?item.targetId:item.id}`,'PUT',{wanted:!item.wanted});await refresh();}catch(e){setError(e instanceof Error?e.message:'未能点菜，请重试');}finally{setBusy(false);}}
 return <div className="want-wrap"><button className={`want-button ${item.wanted?'wanted':''} ${compact?'compact':''}`} aria-label={`${item.wanted?'取消想吃':'想吃'}${'title' in item?' '+item.title:''}`} aria-pressed={item.wanted} disabled={busy||(!live&&!!rater)} onClick={()=>void toggle()}><Icon name="heart" size={17}/><span>{busy?'…':item.wanted?'已想吃':'想吃'}</span>{item.wantEatCount>0&&<small>{item.wantEatCount}</small>}</button>{error&&<span className="inline-error" role="alert">{error}</span>}</div>;
}
export function Card({item,entry,kind,index=1}:{item:Food|Restaurant;entry?:Entry;kind:'dish'|'restaurant';index?:number}){
 const detail=useDetail(),open=()=>detail(entry?'entry':kind,entry?.id||item.id),stats=entry||item;
 return <article className="food-card"><button className="card-picture-button" onClick={open}><Photo url={entry?.coverUrl||item.coverUrl} title={item.title} priority={index<2}/>{entry?.meal&&<span className="meal-badge">{entry.meal}</span>}</button><div className="card-body"><button className="card-title" onClick={open}>{item.title}</button><p className="card-tags">{'location'in item?item.location:tags(item).slice(0,2).join(' · ')}</p>{entry?.notes&&<p className="card-note">{entry.notes}</p>}<div className="card-rating"><span>{stats.ratingAvg===null?'—':score(stats.ratingAvg)}</span><small>{stats.ratingAvg===null?'还没有评分':'/ 10'}</small>{entry?.myScore!=null&&<em>我评 {entry.myScore}</em>}{!entry&&stats.ratingCount>0&&<small>· {stats.ratingCount} 次评价</small>}</div><div className="card-actions"><WantButton item={item} kind={kind} compact/><button className="comment-link" onClick={open} aria-label={`查看${item.title}的评论和详情`}><Icon name="chat" size={16}/>{entry?.commentCount??item.commentCount??0}</button></div></div></article>;
}
